dev/catalyze/forum_modules/exporter/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.utils.translation import ugettext as _

from views import state, running, download

urlpatterns = patterns('',
    url(r'^%s%s%s$' % (_('admin/'), _('exporter/'), _('state/')),  state, name='exporter_state'),
    url(r'^%s(?P<mode>\w+)/%s$' % (_('admin/'), _('running/')),  running, name='exporter_running'),
    url(r'^%s%s%s$' % (_('admin/'), _('exporter/'), _('download/')),  download, name='exporter_download'),
)

dev/catalyze/forum_modules/robotstxt/urls.py
from django.conf.urls.defaults import *
from django.http import  HttpResponse
import settings

urlpatterns = patterns('',
    (r'^robots.txt$',  lambda r: HttpResponse(settings.ROBOTS_FILE.value)),
)

dev/catalyze/forum_modules/updater/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.utils.translation import ugettext as _

from views import updater_index, updater_check

urlpatterns = patterns('',
    url(r'^%s%s%s$' % (_('admin/'), _('updater/'), _('check/')),  updater_check, name='updater_check'),
)

dev/catalyze/urls.py
from django.conf.urls.defaults import *
from django.utils.translation import ugettext as _
from django.conf import settings

urlpatterns = patterns('',
    (r'', include('forum.urls')),
)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

handler404 = 'forum.views.meta.page'
handler500 = 'forum.views.meta.error_handler'

dev/catalyze/forum/models/question.py
from base import *
from tag import Tag
from django.utils.translation import ugettext as _

class QuestionManager(NodeManager):
    def search(self, keywords):
        return False, self.filter(models.Q(title__icontains=keywords) | models.Q(body__icontains=keywords))

class Question(Node):
    class Meta(Node.Meta):
        proxy = True

    answer_count = DenormalizedField("children", ~models.Q(state_string__contains="(deleted)"), node_type="answer")
    accepted_count = DenormalizedField("children", ~models.Q(state_string__contains="(deleted)"), node_type="answer", marked=True)
    favorite_count = DenormalizedField("actions", action_type="favorite", canceled=False)

    friendly_name = _("question")
    objects = QuestionManager()

    @property
    def closed(self):
        return self.nis.closed

    @property    
    def view_count(self):
        return self.extra_count

    @property
    def headline(self):
        if self.nis.deleted:
            return _('[deleted] ') + self.title

        if self.nis.closed:
            return _('[closed] ') + self.title

        return self.title

    @property
    def accepted_answers(self):
        return self.answers.filter(~models.Q(state_string__contains="(deleted)"), marked=True)

    @models.permalink    
    def get_absolute_url(self):
        return ('question', (), {'id': self.id, 'slug': django_urlquote(slugify(self.title))})
        
    def meta_description(self):
        return self.summary

    def get_revision_url(self):
        return reverse('question_revisions', args=[self.id])

    def get_related_questions(self, count=10):
        cache_key = '%s.related_questions:%d:%d' % (settings.APP_URL, count, self.id)
        related_list = cache.get(cache_key)

        if related_list is None:
            related_list = Question.objects.filter_state(deleted=False).values('id').filter(tags__id__in=[t.id for t in self.tags.all()]
            ).exclude(id=self.id).annotate(frequency=models.Count('id')).order_by('-frequency')[:count]
            cache.set(cache_key, related_list, 60 * 60)

        return [Question.objects.get(id=r['id']) for r in related_list]
    



class QuestionSubscription(models.Model):
    user = models.ForeignKey(User)
    question = models.ForeignKey(Node)
    auto_subscription = models.BooleanField(default=True)
    last_view = models.DateTimeField(default=datetime.datetime.now())

    class Meta:
        app_label = 'forum'


class QuestionRevision(NodeRevision):
    class Meta:
        proxy = True
        

dev/catalyze/forum/models/tag.py
import datetime
from base import *

from django.utils.translation import ugettext as _
from django.utils.encoding import smart_unicode, force_unicode

from forum import modules

class ActiveTagManager(CachedManager):
    use_for_related_fields = True

    def get_query_set(self):
        return super(ActiveTagManager, self).get_query_set().exclude(used_count__lt=1)

class Tag(BaseModel):
    name            = models.CharField(max_length=255, unique=True)
    created_by      = models.ForeignKey(User, related_name='created_tags')
    created_at      = models.DateTimeField(default=datetime.datetime.now, blank=True, null=True)
    marked_by       = models.ManyToManyField(User, related_name="marked_tags", through="MarkedTag")
    # Denormalised data
    used_count = models.PositiveIntegerField(default=0)

    active = ActiveTagManager()

    class Meta:
        ordering = ('-used_count', 'name')
        app_label = 'forum'

    def __unicode__(self):
        return force_unicode(self.name)

    def add_to_usage_count(self, value):
        if self.used_count + value < 0:
            self.used_count = 0
        else:
            self.used_count = models.F('used_count') + value

    def cache_key(self):
        return self._generate_cache_key(Tag.safe_cache_name(self.name))

    @classmethod
    def safe_cache_name(cls, name):
        return "".join([str(ord(c)) for c in name])

    @classmethod
    def infer_cache_key(cls, querydict):
        if 'name' in querydict:
            return cls._generate_cache_key(cls.safe_cache_name(querydict['name']))

        return None

    @classmethod
    def value_to_list_on_cache_query(cls):
        return 'name'

    @models.permalink
    def get_absolute_url(self):
        return ('tag_questions', (), {'tag': self.name})

class MarkedTag(models.Model):
    TAG_MARK_REASONS = (('good', _('interesting')), ('bad', _('ignored')))
    tag = models.ForeignKey(Tag, related_name='user_selections')
    user = models.ForeignKey(User, related_name='tag_selections')
    reason = models.CharField(max_length=16, choices=TAG_MARK_REASONS)

    class Meta:
        app_label = 'forum'

dev/catalyze/forum/forms/qanda.py
import re
from datetime import date
from django import forms
from forum.models import *
from django.utils.translation import ugettext as _
from django.contrib.humanize.templatetags.humanize import apnumber

from django.utils.safestring import mark_safe
from general import NextUrlField, UserNameField, SetPasswordForm
from forum import settings

from forum.modules import call_all_handlers

import logging

class TitleField(forms.CharField):
    def __init__(self, *args, **kwargs):
        super(TitleField, self).__init__(*args, **kwargs)
        self.required = True
        self.max_length = 255
        self.widget = forms.TextInput(attrs={'size' : 70, 'autocomplete' : 'off', 'maxlength' : self.max_length})
        self.label  = _('title')
        self.help_text = _('please enter a descriptive title for your question')
        self.initial = ''

    def clean(self, value):
        if len(value) < settings.FORM_MIN_QUESTION_TITLE:
            raise forms.ValidationError(_('title must be must be at least %s characters') % settings.FORM_MIN_QUESTION_TITLE)

        return value

class EditorField(forms.CharField):
    def __init__(self, *args, **kwargs):
        super(EditorField, self).__init__(*args, **kwargs)
        self.widget = forms.Textarea(attrs={'id':'editor'})
        self.label  = _('content')
        self.help_text = u''
        self.initial = ''


class QuestionEditorField(EditorField):
    def __init__(self, *args, **kwargs):
        super(QuestionEditorField, self).__init__(*args, **kwargs)
        self.required = not bool(settings.FORM_EMPTY_QUESTION_BODY)


    def clean(self, value):
        if not bool(settings.FORM_EMPTY_QUESTION_BODY) and (len(re.sub('[ ]{2,}', ' ', value)) < settings.FORM_MIN_QUESTION_BODY):
            raise forms.ValidationError(_('question content must be at least %s characters') % settings.FORM_MIN_QUESTION_BODY)

        return value

class AnswerEditorField(EditorField):
    def __init__(self, *args, **kwargs):
        super(AnswerEditorField, self).__init__(*args, **kwargs)
        self.required = True

    def clean(self, value):
        if len(re.sub('[ ]{2,}', ' ', value)) < settings.FORM_MIN_QUESTION_BODY:
            raise forms.ValidationError(_('answer content must be at least %s characters') % settings.FORM_MIN_QUESTION_BODY)

        return value


class TagNamesField(forms.CharField):
    def __init__(self, user=None, *args, **kwargs):
        super(TagNamesField, self).__init__(*args, **kwargs)
        self.required = True
        self.widget = forms.TextInput(attrs={'size' : 50, 'autocomplete' : 'off'})
        self.max_length = 255
        self.label  = _('tags')
        #self.help_text = _('please use space to separate tags (this enables autocomplete feature)')
        self.help_text = _('Tags are short keywords, with no spaces within. At least %(min)s and up to %(max)s tags can be used.') % {
            'min': settings.FORM_MIN_NUMBER_OF_TAGS, 'max': settings.FORM_MAX_NUMBER_OF_TAGS    
        }
        self.initial = ''
        self.user = user

    def clean(self, value):
        value = super(TagNamesField, self).clean(value)
        data = value.strip().lower()

        split_re = re.compile(r'[ ,]+')
        list = {}
        for tag in split_re.split(data):
            list[tag] = tag

        if len(list) > settings.FORM_MAX_NUMBER_OF_TAGS or len(list) < settings.FORM_MIN_NUMBER_OF_TAGS:
            raise forms.ValidationError(_('please use between %(min)s and %(max)s tags') % { 'min': settings.FORM_MIN_NUMBER_OF_TAGS, 'max': settings.FORM_MAX_NUMBER_OF_TAGS})

        list_temp = []
        tagname_re = re.compile(r'^[\w+\.-]+$', re.UNICODE)
        for key,tag in list.items():
            if len(tag) > settings.FORM_MAX_LENGTH_OF_TAG or len(tag) < settings.FORM_MIN_LENGTH_OF_TAG:
                raise forms.ValidationError(_('please use between %(min)s and %(max)s characters in you tags') % { 'min': settings.FORM_MIN_LENGTH_OF_TAG, 'max': settings.FORM_MAX_LENGTH_OF_TAG})
            if not tagname_re.match(tag):
                raise forms.ValidationError(_('please use following characters in tags: letters , numbers, and characters \'.-_\''))
            # only keep one same tag
            if tag not in list_temp and len(tag.strip()) > 0:
                list_temp.append(tag)

        if settings.LIMIT_TAG_CREATION and not self.user.can_create_tags():
            existent = Tag.objects.filter(name__in=list_temp).values_list('name', flat=True)

            if len(existent) < len(list_temp):
                unexistent = [n for n in list_temp if not n in existent]
                raise forms.ValidationError(_("You don't have enough reputation to create new tags. The following tags do not exist yet: %s") %
                        ', '.join(unexistent))


        return u' '.join(list_temp)

class WikiField(forms.BooleanField):
    def __init__(self, disabled=False, *args, **kwargs):
        super(WikiField, self).__init__(*args, **kwargs)
        self.required = False
        self.label  = _('community wiki')
        self.help_text = _('if you choose community wiki option, the question and answer do not generate points and name of author will not be shown')
        if disabled:
            self.widget=forms.CheckboxInput(attrs={'disabled': "disabled"})
    def clean(self,value):
        return value

class EmailNotifyField(forms.BooleanField):
    def __init__(self, *args, **kwargs):
        super(EmailNotifyField, self).__init__(*args, **kwargs)
        self.required = False
        self.widget.attrs['class'] = 'nomargin'

class SummaryField(forms.CharField):
    def __init__(self, *args, **kwargs):
        super(SummaryField, self).__init__(*args, **kwargs)
        self.required = False
        self.widget = forms.TextInput(attrs={'size' : 50, 'autocomplete' : 'off'})
        self.max_length = 300
        self.label  = _('update summary:')
        self.help_text = _('enter a brief summary of your revision (e.g. fixed spelling, grammar, improved style, this field is optional)')


class FeedbackForm(forms.Form):
    message = forms.CharField(label=_('Your message:'), max_length=800,widget=forms.Textarea(attrs={'cols':60}))
    next = NextUrlField()

    def __init__(self, user, *args, **kwargs):
        super(FeedbackForm, self).__init__(*args, **kwargs)
        if not user.is_authenticated():
            self.fields['name'] = forms.CharField(label=_('Your name:'), required=False)
            self.fields['email'] = forms.EmailField(label=_('Email (not shared with anyone):'), required=True)



class AskForm(forms.Form):
    title  = TitleField()
    text   = QuestionEditorField()

    def __init__(self, data=None, user=None, *args, **kwargs):
        super(AskForm, self).__init__(data, *args, **kwargs)

        self.fields['tags']   = TagNamesField(user)
        
        if int(user.reputation) < settings.CAPTCHA_IF_REP_LESS_THAN and not (user.is_superuser or user.is_staff):
            spam_fields = call_all_handlers('create_anti_spam_field')
            if spam_fields:
                spam_fields = dict(spam_fields)
                for name, field in spam_fields.items():
                    self.fields[name] = field

                self._anti_spam_fields = spam_fields.keys()
            else:
                self._anti_spam_fields = []

        if settings.WIKI_ON:
            self.fields['wiki'] = WikiField()

class AnswerForm(forms.Form):
    text   = AnswerEditorField()
    wiki   = WikiField()

    def __init__(self, data=None, user=None, *args, **kwargs):
        super(AnswerForm, self).__init__(data, *args, **kwargs)
        
        if int(user.reputation) < settings.CAPTCHA_IF_REP_LESS_THAN and not (user.is_superuser or user.is_staff):
            spam_fields = call_all_handlers('create_anti_spam_field')
            if spam_fields:
                spam_fields = dict(spam_fields)
                for name, field in spam_fields.items():
                    self.fields[name] = field

                self._anti_spam_fields = spam_fields.keys()
            else:
                self._anti_spam_fields = []

        if settings.WIKI_ON:
            self.fields['wiki'] = WikiField()

class RetagQuestionForm(forms.Form):
    tags   = TagNamesField()
    # initialize the default values
    def __init__(self, question, *args, **kwargs):
        super(RetagQuestionForm, self).__init__(*args, **kwargs)
        self.fields['tags'].initial = question.tagnames

class RevisionForm(forms.Form):
    """
    Lists revisions of a Question or Answer
    """
    revision = forms.ChoiceField(widget=forms.Select(attrs={'style' : 'width:520px'}))

    def __init__(self, post, *args, **kwargs):
        super(RevisionForm, self).__init__(*args, **kwargs)

        revisions = post.revisions.all().values_list('revision', 'author__username', 'revised_at', 'summary').order_by('-revised_at')

        date_format = '%c'
        self.fields['revision'].choices = [
            (r[0], u'%s - %s (%s) %s' % (r[0], r[1], r[2].strftime(date_format), r[3]))
            for r in revisions]

        self.fields['revision'].initial = post.active_revision.revision

class EditQuestionForm(forms.Form):
    title  = TitleField()
    text   = QuestionEditorField()
    summary = SummaryField()

    def __init__(self, question, user, revision=None, *args, **kwargs):
        super(EditQuestionForm, self).__init__(*args, **kwargs)

        if revision is None:
            revision = question.active_revision

        self.fields['title'].initial = revision.title
        self.fields['text'].initial = revision.body

        self.fields['tags'] = TagNamesField(user)
        self.fields['tags'].initial = revision.tagnames

        if int(user.reputation) < settings.CAPTCHA_IF_REP_LESS_THAN and not (user.is_superuser or user.is_staff):
            spam_fields = call_all_handlers('create_anti_spam_field')
            if spam_fields:
                spam_fields = dict(spam_fields)

dev/catalyze/forum/skins/default/templates/answer_edit.html
{% extends "base.html" %}
<!-- template answer_edit.html -->
{% load i18n %}
{% load extra_tags %}
{% block title %}{% spaceless %}{% trans "Edit answer" %}{% endspaceless %}{% endblock %}
{% block forejs %}
        <script type='text/javascript' src='{% media  "/media/js/wmd/showdown.js" %}'></script>
        <script type='text/javascript' src='{% media  "/media/js/wmd/wmd.js" %}'></script>
        <link rel="stylesheet" type="text/css" href="{% media  "/media/js/wmd/wmd.css" %}" />
        <script type="text/javascript">
        
        $().ready(function(){
            $("#nav_questions").attr('className',"on");
            $('#editor').TextAreaResizer();


            //toggle preview of editor
            var display = true;
            var txt = "{% trans "hide preview" %}";
            $('#pre-collapse').text(txt);
            $('#pre-collapse').bind('click', function(){
                txt = display ? "{% trans "show preview" %}" : "{% trans "hide preview" %}";
                display = !display;
                $('#previewer').toggle();
                $('#pre-collapse').text(txt);
            });


            $('#id_revision').unbind().change(function(){
                $("#select_revision").click();
            });


            answer = $("textarea#editor")[0].value;
        });


        function submitClicked(e, f) {
            if(!(browserTester('chrome') || browserTester('safari'))) {
                $("input.submit")[0].disabled=true;
                $("input.submit")[1].disabled=true;
            }
            window.removeEventListener('beforeunload', beforeUnload, true);
            if (f) {
                f.submit();
            }
        }

        function beforeUnload(e) {
            if($("textarea#editor")[0].value != answer) {
                 return yourWorkWillBeLost(e);
            }
        }
        window.addEventListener('beforeunload', beforeUnload, true);

        var answer = "";
        </script>
{% endblock %}
        
{% block content %}
<div id="main-bar" class="headNormal">
    {% trans "Edit answer" %} [<a href="{{ answer.question.get_absolute_url }}#{{ answer.id }}">{% trans "back" %}</a>]
</div>
<div id="main-body" class="ask-body">
    <div id="askform">
        <form id="fmedit" action="{% url edit_answer answer.id %}" method="post">
            {% csrf_token %}
            <label for="id_revision" ><strong>{% trans "revision" %}:</strong></label> <br/> 
            {% if revision_form.revision.errors %}{{ revision_form.revision.errors.as_ul }}{% endif %}
            <div>
            {{ revision_form.revision }} <input type="submit" style="display:none" id="select_revision" name="select_revision" value="{% trans "select revision" %}">
            </div>
            <div class="form-item">
                <div id="wmd-button-bar" class="wmd-panel"></div>
                {{ form.text }}
                <span class="form-error"></span>
                <div class="preview-toggle"><span id="pre-collapse" 
					title="{% trans "Toggle the real time Markdown editor preview" %}">{% trans "toggle preview" %}</span>
			    <span style="text-align: right; margin-left: 200px;" id="editor-metrics"></span>
				{% if settings.WIKI_ON %}
                    <div style="float:right;">
                        {{ form.wiki }} <span style="color:#000;cursor:help" title="{{form.wiki.help_text}}">{{ form.wiki.label_tag }} </span>
                    </div>
                    {% endif %}
                </div>
                <div id="previewer" class="wmd-preview"></div>
            </div>
            
            <strong>{{ form.summary.label_tag }}</strong> <br/>
            {{ form.summary }}  {{ form.summary.errors }}
            <div class="title-desc">
                {{ form.summary.help_text }}
            </div>
            
            {% if form.recaptcha %}
            <div class="question-captcha">
            	{{ form.recaptcha.errors }}
            	{{ form.recaptcha }}
            </div>
            {% endif %}
            
            <input type="button" value="{% trans "Save edit" %}" class="submit" onclick="submitClicked(event, this.form)" />
            <input type="button" value="{% trans "Cancel" %}" class="submit" onclick="submitClicked(event, this.form);history.back(-1);" />
        </form>
    </div>
</div>
{% endblock %}

{% block sidebar %}
{% include "answer_edit_tips.html" %}
{% endblock %}

{% block endjs %}
{% endblock %}
<!-- end template answer_edit.html -->

dev/catalyze/forum/skins/default/templates/base.html
{% extends "base_content.html" %}
{% block page_center %}

{% block full_width_banner %}{% endblock %}

<div id="wrapper">
    {% block site_width_banner %}{% endblock %}
    
    <div id="room">
        <div id="CALeft">
            {% block content%}
            {% endblock%}

        </div>
        <div id="CARight">
            {% block sidebar%}
            {% endblock%}

        </div>
        <div id="tail" style="clear:both;">
            {% block tail %}
            {% endblock %}
        </div>
    </div>
    <div class="spacer3"></div>
</div>
{% endblock %}

dev/catalyze/forum/skins/default/templates/footer.html
{% load extra_tags ui_registry i18n %}


<div>
    <div class="footerLinks" >
        {% loadregistry footer_links %}<span class="link-separator"> |</span>{% endloadregistry %}
    </div>
  <p>
     <a href="http://osqa.net" target="_blank" title="OSQA {{ settings.OSQA_VERSION }} ({{ settings.SVN_REVISION }})">
        powered by OSQA
     </a>
  </p>
</div>
 <div id="licenseLogo">
  <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/">
            <img src="{% media  "/media/images/by-sa-88x31.png" %}" title="Creative Commons: Attribution - Share Alike" alt="cc-by-sa" width="88" height="31" />
  </a>
 </div>

dev/catalyze/forum/skins/default/templates/header.html
<!-- template header.html -->
{% load extra_tags ui_registry i18n extra_filters markup %}

	<div id="roof">
	  
		<div id="logo">
			<a href="{% url index %}">
				<img src="{{ settings.APP_LOGO }}" title="{% trans "back to home page" %}" alt="{{settings.APP_TITLE}} logo"/>
			</a>
		</div>
	  
		<div id="top">
		    {% loadregistry header_links %}{% endloadregistry %}
		</div>

    <div id="nav">
        {% loopregistry page_top_tabs %}{% spaceless %}
            <a id="nav_{{ tab_name }}"{% ifequal tab tab_name %} class="on"{% endifequal %} href="{{ tab_url }}" >{{ tab_title }}</a>
        {% endspaceless %}{% endloopregistry %}
        <a id="nav_ask" href="{% url ask %}" class="special">{% trans "ask a question" %}</a>
    </div>
  </div>

  <div class="clear"></div>
  
	<div id="searchBar">
    <form action="{% url search %}" method="get">
        {% csrf_token %}
        <div>
            <input type="text" class="searchInput" value="{{ keywords }}" name="q" id="keywords" />
            <input type="submit" name="Submit" value="{% trans "search" %}" class="searchBtn" />
        </div>
        <div class="options">
            <input id="type-question" type="radio" value="question" name="t" 
                checked="checked" /><label for="type-question">{% trans "questions" %}</label>
            <input id="type-tag" type="radio" value="tag" name="t" /><label for="type-tag">{% trans "tags" %}</label>
            <input id="type-user" type="radio" value="user" name="t" /><label for="type-user">{% trans "users" %}</label>
        </div>
    </form>	
	</div>

	{% if settings.USE_ANNOUNCEMENT_BAR|or_preview:request %}
  <div id="announcement">
      {{ settings.ANNOUNCEMENT_BAR|or_preview:request|static_content:settings.ANNOUNCEMENT_BAR_RENDER_MODE }}
  </div>
  {% endif %}

<!-- end template header.html -->

dev/catalyze/forum/skins/default/templates/opensearch.html
{% load i18n %}
<?xml version="1.0" encoding="UTF-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
   <ShortName>{{ settings.APP_SHORT_NAME }} {% trans "Search" %}</ShortName>
   <Description>{% trans "Search" %} {{ settings.APP_SHORT_NAME }} {% trans "using your browser." %}</Description>
   <Tags>{{ settings.APP_KEYWORDS }}</Tags>
   <Url type="text/html" template="{{ settings.APP_URL }}/{% trans "search" %}/?q={searchTerms}&amp;t=question"/>
</OpenSearchDescription>

dev/catalyze/forum/skins/default/templates/pagesize.html
<!-- template pagesize.html -->
{% spaceless %}
{% load i18n %}
{% if is_paginated %}
<div class="paginator">
    <span class="text">{% trans "posts per page" %}</span>
    {% ifequal pagesize 10 %}
        <span class="curr">10</span>
    {% else %}
        <span class="page"><a href="{{base_url}}pagesize=10">10</a></span>
    {% endifequal %}
    
    {% ifequal pagesize 30 %}
        <span class="curr">30</span>
    {% else %}
        <span class="page"><a href="{{base_url}}pagesize=30">30</a></span>
    {% endifequal %}
    
    {% ifequal pagesize 50 %}
        <span class="curr">50</span>
    {% else %}
        <span class="page"><a href="{{base_url}}pagesize=50">50</a></span>
    {% endifequal %}
</div> 
{% endif %}
{% endspaceless %}
<!-- end template pagesize.html -->

dev/catalyze/forum/skins/default/templates/paginator.html
<!-- paginator.html -->
{% spaceless %}
{% load i18n %}
{% if is_paginated %}
<div class="paginator">
{% if has_previous %}<span class="prev"><a href="{{base_url}}page={{ previous }}{{ extend_url }}" title="{% trans "previous" %}">
&laquo; {% trans "previous" %}</a></span>{% endif %}
{% if not in_leading_range %}
	{% for num in pages_outside_trailing_range %}
		<span class="page"><a href="{{base_url}}page={{ num }}{{ extend_url }}" >{{ num }}</a></span>
	{% endfor %}
	...
{% endif %}
 
{% for num in page_numbers %}
  {% ifequal num page %}
    {% ifequal pages 1 %}
    {% else %}
    <span class="curr" title="{% trans "current page" %}">{{ num }}</span>
    {% endifequal %}
  {% else %}
  	<span class="page"><a href="{{base_url}}page={{ num }}{{ extend_url }}" title="{% trans "page number " %}{{ num }}{% trans "number - make blank in english" %}">{{ num }}</a></span>
  {% endifequal %}
{% endfor %}
 
{% if not in_trailing_range %}
	...
	{% for num in pages_outside_leading_range reversed %}
		<span class="page"><a href="{{base_url}}page={{ num }}{{ extend_url }}" title="{% trans "page number " %}{{ num }}{% trans "number - make blank in english" %}">{{ num }}</a></span>
	{% endfor %}
{% endif %}
 
{% if has_next %}<span class="next"><a href="{{base_url}}page={{ next }}{{ extend_url }}" title="{% trans "next page" %}">{% trans "next page" %} &raquo;</a></span>{% endif %}
</div> 
{% endif %}
 
{% endspaceless %}
<!-- end paginator.html -->

dev/catalyze/forum/skins/default/templates/privacy.html
{% extends "base_content.html" %}
<!-- privacy.html -->
{% load extra_tags %}
{% load i18n %}
{% load humanize %}
{% block title %}{% spaceless %}{% trans "Privacy policy" %}{% endspaceless %}{% endblock %}
{% block forejs %}
{% endblock %}
{% block content %}
<div class="headNormal">
	{% trans "Privacy policy" %}
</div>
<div id="main-body" style="width:100%">
    <p>
		{% trans "general message about privacy" %}
    </p>
    
        <h3 class="subtitle">{% trans "Site Visitors" %}</h3>
    <p>    
	{% trans "what technical information is collected about visitors" %}
    </p>
    
        <h3 class="subtitle">{% trans "Personal Information" %}</h3>
    <p>   
		{% trans "details on personal information policies" %}
    </p>
   
        <h3 class="subtitle">{% trans "Other Services" %}</h3>
     <p>   
	 {% trans "details on sharing data with third parties" %}
    </p>
    
        <h3 class="subtitle">Cookies</h3>
    <p>
		{% trans "cookie policy details" %}
    </p>
        <h3 class="subtitle">{% trans "Policy Changes" %}</h3>
    <p>{% trans "how privacy policies can be changed" %}
    </p>
</div>
{% endblock %}
<!-- end privacy.html -->